from blackjack.values import HandState, BANK_STARTING_CARDS, PLAYER_STARTING_STATES
import numpy as np

# Given hand value (key of TRANSITIONS dict) and car value (key of the subdict),
# value is the result obtained after a hit (or double) action
# no value = hand is burned
HIT_TRANSITIONS = {
    # Figure is used to represent a single 10 or figure card
    # Ten is used to represent a ten score with 2 or more cards (6+4 or 5+5 or 7+3)
    # This is to distinguish the blackjack case: you can transition to blackjack with a single ten
    # but not with a 2-cards 10 score
    HandState.BUST: {},
    HandState.TWO: {
        HandState.ACE: HandState.THREE_THIRTEEN,
        HandState.TWO: HandState.FOUR,
        HandState.THREE: HandState.FIVE,
        HandState.FOUR: HandState.SIX,
        HandState.FIVE: HandState.SEVEN,
        HandState.SIX: HandState.EIGHT,
        HandState.SEVEN: HandState.NINE,
        HandState.EIGHT: HandState.TEN,
        HandState.NINE: HandState.ELEVEN,
        HandState.FIGURE: HandState.TWELVE,
    },
    HandState.THREE: {
        HandState.ACE: HandState.FOUR_FOURTEEN,
        HandState.TWO: HandState.FIVE,
        HandState.THREE: HandState.SIX,
        HandState.FOUR: HandState.SEVEN,
        HandState.FIVE: HandState.EIGHT,
        HandState.SIX: HandState.NINE,
        HandState.SEVEN: HandState.TEN,
        HandState.EIGHT: HandState.ELEVEN,
        HandState.NINE: HandState.TWELVE,
        HandState.FIGURE: HandState.THIRTEEN,
    },
    HandState.FOUR: {
        HandState.ACE: HandState.FIVE_FIFTEEN,
        HandState.TWO: HandState.SIX,
        HandState.THREE: HandState.SEVEN,
        HandState.FOUR: HandState.EIGHT,
        HandState.FIVE: HandState.NINE,
        HandState.SIX: HandState.TEN,
        HandState.SEVEN: HandState.ELEVEN,
        HandState.EIGHT: HandState.TWELVE,
        HandState.NINE: HandState.THIRTEEN,
        HandState.FIGURE: HandState.FOURTEEN,
    },
    HandState.FIVE: {
        HandState.ACE: HandState.SIX_SIXTEEN,
        HandState.TWO: HandState.SEVEN,
        HandState.THREE: HandState.EIGHT,
        HandState.FOUR: HandState.NINE,
        HandState.FIVE: HandState.TEN,
        HandState.SIX: HandState.ELEVEN,
        HandState.SEVEN: HandState.TWELVE,
        HandState.EIGHT: HandState.THIRTEEN,
        HandState.NINE: HandState.THIRTEEN,
        HandState.FIGURE: HandState.FIFTEEN,
    },
    HandState.SIX: {
        HandState.ACE: HandState.SEVEN_SEVENTEEN,
        HandState.TWO: HandState.EIGHT,
        HandState.THREE: HandState.NINE,
        HandState.FOUR: HandState.TEN,
        HandState.FIVE: HandState.ELEVEN,
        HandState.SIX: HandState.TWELVE,
        HandState.SEVEN: HandState.THIRTEEN,
        HandState.EIGHT: HandState.FOURTEEN,
        HandState.NINE: HandState.FIFTEEN,
        HandState.FIGURE: HandState.SIXTEEN,
    },
    HandState.SEVEN: {
        HandState.ACE: HandState.EIGHT_EIGHTEEN,
        HandState.TWO: HandState.NINE,
        HandState.THREE: HandState.TEN,
        HandState.FOUR: HandState.ELEVEN,
        HandState.FIVE: HandState.TWELVE,
        HandState.SIX: HandState.THIRTEEN,
        HandState.SEVEN: HandState.FOURTEEN,
        HandState.EIGHT: HandState.FIFTEEN,
        HandState.NINE: HandState.SIXTEEN,
        HandState.FIGURE: HandState.SEVENTEEN,
    },
    HandState.EIGHT: {
        HandState.ACE: HandState.NINE_NINETEEN,
        HandState.TWO: HandState.TEN,
        HandState.THREE: HandState.ELEVEN,
        HandState.FOUR: HandState.TWELVE,
        HandState.FIVE: HandState.THIRTEEN,
        HandState.SIX: HandState.FOURTEEN,
        HandState.SEVEN: HandState.FIFTEEN,
        HandState.EIGHT: HandState.SIXTEEN,
        HandState.NINE: HandState.SEVENTEEN,
        HandState.FIGURE: HandState.EIGHTEEN,
    },
    HandState.NINE: {
        HandState.ACE: HandState.TEN_TWENTY,
        HandState.TWO: HandState.ELEVEN,
        HandState.THREE: HandState.TWELVE,
        HandState.FOUR: HandState.THIRTEEN,
        HandState.FIVE: HandState.FOURTEEN,
        HandState.SIX: HandState.FIFTEEN,
        HandState.SEVEN: HandState.SIXTEEN,
        HandState.EIGHT: HandState.SEVENTEEN,
        HandState.NINE: HandState.EIGHTEEN,
        HandState.FIGURE: HandState.NINETEEN,
    },
    HandState.TEN: {
        HandState.ACE: HandState.TWENTY_ONE,
        HandState.TWO: HandState.TWELVE,
        HandState.THREE: HandState.THIRTEEN,
        HandState.FOUR: HandState.FOURTEEN,
        HandState.FIVE: HandState.FIFTEEN,
        HandState.SIX: HandState.SIXTEEN,
        HandState.SEVEN: HandState.SEVENTEEN,
        HandState.EIGHT: HandState.EIGHTEEN,
        HandState.NINE: HandState.NINETEEN,
        HandState.FIGURE: HandState.TWENTY,
    },
    HandState.FIGURE: {
        HandState.ACE: HandState.BLACKJACK,
        HandState.TWO: HandState.TWELVE,
        HandState.THREE: HandState.THIRTEEN,
        HandState.FOUR: HandState.FOURTEEN,
        HandState.FIVE: HandState.FIFTEEN,
        HandState.SIX: HandState.SIXTEEN,
        HandState.SEVEN: HandState.SEVENTEEN,
        HandState.EIGHT: HandState.EIGHTEEN,
        HandState.NINE: HandState.NINETEEN,
        HandState.FIGURE: HandState.TWENTY,
    },
    HandState.ELEVEN: {
        HandState.ACE: HandState.TWELVE,
        HandState.TWO: HandState.THIRTEEN,
        HandState.THREE: HandState.FOURTEEN,
        HandState.FOUR: HandState.FIFTEEN,
        HandState.FIVE: HandState.SIXTEEN,
        HandState.SIX: HandState.SEVENTEEN,
        HandState.SEVEN: HandState.EIGHTEEN,
        HandState.EIGHT: HandState.NINETEEN,
        HandState.NINE: HandState.TWENTY,
        HandState.FIGURE: HandState.TWENTY_ONE,
    },
    HandState.TWELVE: {
        HandState.ACE: HandState.THIRTEEN,
        HandState.TWO: HandState.FOURTEEN,
        HandState.THREE: HandState.FIFTEEN,
        HandState.FOUR: HandState.SIXTEEN,
        HandState.FIVE: HandState.SEVENTEEN,
        HandState.SIX: HandState.EIGHTEEN,
        HandState.SEVEN: HandState.NINETEEN,
        HandState.EIGHT: HandState.TWENTY,
        HandState.NINE: HandState.TWENTY_ONE,
    },
    HandState.THIRTEEN: {
        HandState.ACE: HandState.FOURTEEN,
        HandState.TWO: HandState.FIFTEEN,
        HandState.THREE: HandState.SIXTEEN,
        HandState.FOUR: HandState.SEVENTEEN,
        HandState.FIVE: HandState.EIGHTEEN,
        HandState.SIX: HandState.NINETEEN,
        HandState.SEVEN: HandState.TWENTY,
        HandState.EIGHT: HandState.TWENTY_ONE,
    },
    HandState.FOURTEEN: {
        HandState.ACE: HandState.FIFTEEN,
        HandState.TWO: HandState.SIXTEEN,
        HandState.THREE: HandState.SEVENTEEN,
        HandState.FOUR: HandState.EIGHTEEN,
        HandState.FIVE: HandState.NINETEEN,
        HandState.SIX: HandState.TWENTY,
        HandState.SEVEN: HandState.TWENTY_ONE,
    },
    HandState.FIFTEEN: {
        HandState.ACE: HandState.SIXTEEN,
        HandState.TWO: HandState.SEVENTEEN,
        HandState.THREE: HandState.EIGHTEEN,
        HandState.FOUR: HandState.NINETEEN,
        HandState.FIVE: HandState.TWENTY,
        HandState.SIX: HandState.TWENTY_ONE,
    },
    HandState.SIXTEEN: {
        HandState.ACE: HandState.SEVENTEEN,
        HandState.TWO: HandState.EIGHTEEN,
        HandState.THREE: HandState.NINETEEN,
        HandState.FOUR: HandState.TWENTY,
        HandState.FIVE: HandState.TWENTY_ONE,
    },
    HandState.SEVENTEEN: {
        HandState.ACE: HandState.EIGHTEEN,
        HandState.TWO: HandState.NINETEEN,
        HandState.THREE: HandState.TWENTY,
        HandState.FOUR: HandState.TWENTY_ONE,
    },
    HandState.EIGHTEEN: {
        HandState.ACE: HandState.NINETEEN,
        HandState.TWO: HandState.TWENTY,
        HandState.THREE: HandState.TWENTY_ONE,
    },
    HandState.NINETEEN: {
        HandState.ACE: HandState.TWENTY,
        HandState.TWO: HandState.TWENTY_ONE,
    },
    HandState.TWENTY: {
        HandState.ACE: HandState.TWENTY_ONE,
    },
    # Soft hands
    HandState.ACE: {
        HandState.ACE: HandState.TWO_TWELVE,
        HandState.TWO: HandState.THREE_THIRTEEN,
        HandState.THREE: HandState.FOUR_FOURTEEN,
        HandState.FOUR: HandState.FIVE_FIFTEEN,
        HandState.FIVE: HandState.SIX_SIXTEEN,
        HandState.SIX: HandState.SEVEN_SEVENTEEN,
        HandState.SEVEN: HandState.EIGHT_EIGHTEEN,
        HandState.EIGHT: HandState.NINE_NINETEEN,
        HandState.NINE: HandState.TEN_TWENTY,
        HandState.FIGURE: HandState.BLACKJACK,
    },
    HandState.ACE_S: {  # special case for the Ace that come from a pocket aces split
        HandState.ACE: HandState.TWELVE,
        HandState.TWO: HandState.THIRTEEN,
        HandState.THREE: HandState.FOURTEEN,
        HandState.FOUR: HandState.FIFTEEN,
        HandState.FIVE: HandState.SIXTEEN,
        HandState.SIX: HandState.SEVENTEEN,
        HandState.SEVEN: HandState.EIGHTEEN,
        HandState.EIGHT: HandState.NINETEEN,
        HandState.NINE: HandState.TWENTY,
        HandState.FIGURE: HandState.TWENTY_ONE,
    },
    HandState.TWO_TWELVE: {
        HandState.ACE: HandState.THREE_THIRTEEN,
        HandState.TWO: HandState.FOUR_FOURTEEN,
        HandState.THREE: HandState.FIVE_FIFTEEN,
        HandState.FOUR: HandState.SIX_SIXTEEN,
        HandState.FIVE: HandState.SEVEN_SEVENTEEN,
        HandState.SIX: HandState.EIGHT_EIGHTEEN,
        HandState.SEVEN: HandState.NINE_NINETEEN,
        HandState.EIGHT: HandState.TEN_TWENTY,
        HandState.NINE: HandState.TWENTY_ONE,
        HandState.FIGURE: HandState.TWELVE,
    },
    HandState.THREE_THIRTEEN: {
        HandState.ACE: HandState.FOUR_FOURTEEN,
        HandState.TWO: HandState.FIVE_FIFTEEN,
        HandState.THREE: HandState.SIX_SIXTEEN,
        HandState.FOUR: HandState.SEVEN_SEVENTEEN,
        HandState.FIVE: HandState.EIGHT_EIGHTEEN,
        HandState.SIX: HandState.NINE_NINETEEN,
        HandState.SEVEN: HandState.TEN_TWENTY,
        HandState.EIGHT: HandState.TWENTY_ONE,
        HandState.NINE: HandState.TWELVE,
        HandState.FIGURE: HandState.THIRTEEN,
    },
    HandState.FOUR_FOURTEEN: {
        HandState.ACE: HandState.FIVE_FIFTEEN,
        HandState.TWO: HandState.SIX_SIXTEEN,
        HandState.THREE: HandState.SEVEN_SEVENTEEN,
        HandState.FOUR: HandState.EIGHT_EIGHTEEN,
        HandState.FIVE: HandState.NINE_NINETEEN,
        HandState.SIX: HandState.TEN_TWENTY,
        HandState.SEVEN: HandState.TWENTY_ONE,
        HandState.EIGHT: HandState.TWELVE,
        HandState.NINE: HandState.THIRTEEN,
        HandState.FIGURE: HandState.FOURTEEN,
    },
    HandState.FIVE_FIFTEEN: {
        HandState.ACE: HandState.SIX_SIXTEEN,
        HandState.TWO: HandState.SEVEN_SEVENTEEN,
        HandState.THREE: HandState.EIGHT_EIGHTEEN,
        HandState.FOUR: HandState.NINE_NINETEEN,
        HandState.FIVE: HandState.TEN_TWENTY,
        HandState.SIX: HandState.TWENTY_ONE,
        HandState.SEVEN: HandState.TWELVE,
        HandState.EIGHT: HandState.THIRTEEN,
        HandState.NINE: HandState.FOURTEEN,
        HandState.FIGURE: HandState.FIFTEEN,
    },
    HandState.SIX_SIXTEEN: {
        HandState.ACE: HandState.SEVEN_SEVENTEEN,
        HandState.TWO: HandState.EIGHT_EIGHTEEN,
        HandState.THREE: HandState.NINE_NINETEEN,
        HandState.FOUR: HandState.TEN_TWENTY,
        HandState.FIVE: HandState.TWENTY_ONE,
        HandState.SIX: HandState.TWELVE,
        HandState.SEVEN: HandState.THIRTEEN,
        HandState.EIGHT: HandState.FOURTEEN,
        HandState.NINE: HandState.FIFTEEN,
        HandState.FIGURE: HandState.SIXTEEN,
    },
    HandState.SEVEN_SEVENTEEN: {
        HandState.ACE: HandState.EIGHT_EIGHTEEN,
        HandState.TWO: HandState.NINE_NINETEEN,
        HandState.THREE: HandState.TEN_TWENTY,
        HandState.FOUR: HandState.TWENTY_ONE,
        HandState.FIVE: HandState.TWELVE,
        HandState.SIX: HandState.THIRTEEN,
        HandState.SEVEN: HandState.FOURTEEN,
        HandState.EIGHT: HandState.FIFTEEN,
        HandState.NINE: HandState.SIXTEEN,
        HandState.FIGURE: HandState.SEVENTEEN,
    },
    HandState.EIGHT_EIGHTEEN: {
        HandState.ACE: HandState.NINE_NINETEEN,
        HandState.TWO: HandState.TEN_TWENTY,
        HandState.THREE: HandState.TWENTY_ONE,
        HandState.FOUR: HandState.TWELVE,
        HandState.FIVE: HandState.THIRTEEN,
        HandState.SIX: HandState.FOURTEEN,
        HandState.SEVEN: HandState.FIFTEEN,
        HandState.EIGHT: HandState.SIXTEEN,
        HandState.NINE: HandState.SEVENTEEN,
        HandState.FIGURE: HandState.EIGHTEEN,
    },
    HandState.NINE_NINETEEN: {
        HandState.ACE: HandState.TEN_TWENTY,
        HandState.TWO: HandState.TWENTY_ONE,
        HandState.THREE: HandState.TWELVE,
        HandState.FOUR: HandState.THIRTEEN,
        HandState.FIVE: HandState.FOURTEEN,
        HandState.SIX: HandState.FIFTEEN,
        HandState.SEVEN: HandState.SIXTEEN,
        HandState.EIGHT: HandState.SEVENTEEN,
        HandState.NINE: HandState.EIGHTEEN,
        HandState.FIGURE: HandState.NINETEEN,
    },
    HandState.TEN_TWENTY: {
        HandState.ACE: HandState.TWENTY_ONE,
        HandState.TWO: HandState.TWELVE,
        HandState.THREE: HandState.THIRTEEN,
        HandState.FOUR: HandState.FOURTEEN,
        HandState.FIVE: HandState.FIFTEEN,
        HandState.SIX: HandState.SIXTEEN,
        HandState.SEVEN: HandState.SEVENTEEN,
        HandState.EIGHT: HandState.EIGHTEEN,
        HandState.NINE: HandState.NINETEEN,
        HandState.FIGURE: HandState.TWENTY,
    },
}
# Add pocket hands transitions
HIT_TRANSITIONS[HandState.POCKET_ACE] = HIT_TRANSITIONS[HandState.TWO_TWELVE]
HIT_TRANSITIONS[HandState.POCKET_TWO] = HIT_TRANSITIONS[HandState.FOUR]
HIT_TRANSITIONS[HandState.POCKET_THREE] = HIT_TRANSITIONS[HandState.SIX]
HIT_TRANSITIONS[HandState.POCKET_FOUR] = HIT_TRANSITIONS[HandState.EIGHT]
HIT_TRANSITIONS[HandState.POCKET_FIVE] = HIT_TRANSITIONS[HandState.TEN]
HIT_TRANSITIONS[HandState.POCKET_SIX] = HIT_TRANSITIONS[HandState.TWELVE]
HIT_TRANSITIONS[HandState.POCKET_SEVEN] = HIT_TRANSITIONS[HandState.FOURTEEN]
HIT_TRANSITIONS[HandState.POCKET_EIGHT] = HIT_TRANSITIONS[HandState.SIXTEEN]
HIT_TRANSITIONS[HandState.POCKET_NINE] = HIT_TRANSITIONS[HandState.EIGHTEEN]
HIT_TRANSITIONS[HandState.POCKET_FIGURE] = HIT_TRANSITIONS[HandState.TWENTY]

HIT_PROBABILITIES = {
    HandState.ACE: 1 / 13,
    HandState.TWO: 1 / 13,
    HandState.THREE: 1 / 13,
    HandState.FOUR: 1 / 13,
    HandState.FIVE: 1 / 13,
    HandState.SIX: 1 / 13,
    HandState.SEVEN: 1 / 13,
    HandState.EIGHT: 1 / 13,
    HandState.NINE: 1 / 13,
    HandState.FIGURE: 4 / 13,
}
